version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock # Need this to restart OSRM containers from backend
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    restart: always

  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: osrm_portal
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  osrm-car:
    image: osrm/osrm-backend
    ports:
      - "5002:5000"
    volumes:
      - ./data:/data
    command: "osrm-routed --algorithm mld /data/car.osrm"
    restart: always

  osrm-foot:
    image: osrm/osrm-backend
    ports:
      - "5003:5000"
    volumes:
      - ./data:/data
    command: "osrm-routed --algorithm mld /data/foot.osrm"
    restart: always

volumes:
  db_data:
